import {
  AlertCircleIcon,
  AlertIcon,
  BastIcon,
  BastLogoFullIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronUpIcon,
  CloseIcon,
  GlassesIcon,
  LogInIcon,
  LogOutIcon,
  MoonIcon,
  MoreVerticalIcon,
  OptionsIcon,
  PersonIcon,
  RainIcon,
  SettingsIcon,
  SkatLogoFullIcon,
  SnowIcon,
  SpinnerIcon,
  SunIcon,
  WaterIcon,
} from '../../assets';
import { TBastColor } from '../../lib';

export const Icons = {
  Check: CheckIcon,
  Close: CloseIcon,
  Bast: BastIcon,
  Alert: AlertIcon,
  AlertCircle: AlertCircleIcon,
  CheckCircle: CheckCircleIcon,
  ChevronUp: ChevronUpIcon,
  Spinner: SpinnerIcon,
  BastLogoFull: BastLogoFullIcon,
  SkatLogoFull: SkatLogoFullIcon,
  MoreVertical: MoreVerticalIcon,
  Person: PersonIcon,
  Sun: SunIcon,
  Glasses: GlassesIcon,
  Moon: MoonIcon,
  LogIn: LogInIcon,
  LogOut: LogOutIcon,
  Options: OptionsIcon,
  Settings: SettingsIcon,
  Rain: RainIcon,
  Snow: SnowIcon,
  Water: WaterIcon,
};

export type TIcons = keyof typeof Icons;

export const BAST_ICONS_BY_COLOR: Record<TBastColor, TIcons> = {
  brand: 'Bast',
  gray: 'Bast',
  warning: 'Alert',
  danger: 'AlertCircle',
  success: 'CheckCircle',
};
